import { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Building2, Mail, MapPin, Phone, Plus, Ruler, ShieldCheck, Trees } from 'lucide-react';
import ResponsiveImage from '../components/ResponsiveImage.jsx';
import Footer from '../components/Footer.jsx';
import { RouteHeader } from './PageShared.jsx';
import { usePageSeo, buildFaqSchema } from '../hooks/usePageSeo.js';
import { routeGroups } from '../data/navigation.js';
import { palomaGreensSeo, palomaGreensFaqs, palomaGreensReasons } from '../data/palomaGreensContent.js';
import '../styles/palam-city.css';

export const seo = palomaGreensSeo;
const faqSchema = buildFaqSchema(palomaGreensFaqs);
const sections = [['pg-overview', 'Overview'], ['pg-plots', 'Plots'], ['pg-location', 'Location'], ['pg-faq', 'FAQs'], ['pg-contact', 'Enquire']];
const colonisers = '/about#business-verticals';

export default function PalomaGreensPage() {
  const [active, setActive] = useState('pg-overview');
  usePageSeo({ ...seo, structuredData: faqSchema, structuredDataKey: 'paloma-greens-faq' });
  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: '-15% 0px -55% 0px' });
    sections.forEach(([id]) => { const section = document.getElementById(id); if (section) observer.observe(section); });
    return () => observer.disconnect();
  }, []);

  return <div className="route-page pc-shell pg-shell">
    <a className="skip-link" href="#main">Skip to content</a><RouteHeader />
    <main id="main" className="pc-page pg-page">
      <section className="pc-hero mobile-photo-hero" aria-labelledby="pg-title"><div className="container pc-hero-grid">
        <div className="pc-hero-copy"><nav className="pc-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href={colonisers}>Pal Colonisers</a><span>/</span><span aria-current="page">Paloma Greens</span></nav><p className="eyebrow">Pal Colonisers · Residential</p><h1 id="pg-title">Paloma Greens,<br /><em>luxury living surrounded by nature in Haldwani</em></h1><p>Paloma Greens brings together luxury, nature, and modern living in one Haldwani community, with plots designed for the home you want to build.</p><div className="hero-actions"><a className="button button-brass" href="#pg-contact">Enquire about Paloma Greens <ArrowUpRight size={18} /></a><a className="pc-explore" href="#pg-overview">Explore Paloma Greens <ArrowDownRight size={20} /></a></div><div className="pc-hero-signoff"><span>By <a href={colonisers}>Pal Colonisers</a></span><span>Part of <a href="/about/the-pal-group">SM Pal Group</a></span></div></div>
        <figure className="pc-hero-photo"><ResponsiveImage src="/assets/Palam City -1.jpg.webp" alt="Residential community visual for Paloma Greens in Haldwani" fetchPriority="high" sizes="(max-width: 800px) 100vw, 55vw" /><figcaption><MapPin size={17} /> A greener address in Haldwani</figcaption></figure>
      </div></section>
      <nav className="pc-section-nav" aria-label="On this page"><div className="container">{sections.map(([id, title], i) => <a key={id} href={`#${id}`} aria-current={active === id ? 'location' : undefined}><span>0{i + 1}</span>{title}</a>)}</div></nav>
      <section className="section-pad pc-overview" id="pg-overview" aria-labelledby="pg-overview-title"><div className="container"><div className="pc-split"><div><p className="eyebrow eyebrow-dark">01 / About Paloma Greens</p><h2 id="pg-overview-title">Luxury living.<br /><em>Closer to nature.</em></h2></div><div className="pc-prose"><p>Paloma Greens is a residential project by <a href={colonisers}>Pal Colonisers</a>, part of <a href="/about/the-pal-group">SM Pal Group's</a> real estate portfolio, built around a straightforward promise: luxury living without losing your connection to nature.</p><p>The project is designed for buyers who want a home that feels genuinely settled into its surroundings, not built on top of them.</p></div></div><div className="pc-at-glance">{[[Ruler, 'Flexible plot sizes', '1,000 to 2,000 sq ft'], [Trees, 'A nature-forward setting', 'Luxury and green space together'], [ShieldCheck, 'A trusted developer', 'Pal Colonisers and SM Pal Group']].map(([Icon, title, text]) => <div key={title}><Icon size={26} strokeWidth={1.5} /><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>
      <section className="section-pad pc-living" id="pg-plots" aria-labelledby="pg-plots-title"><div className="container"><div className="pc-heading"><p className="eyebrow eyebrow-dark">02 / Plots to match your lifestyle</p><h2 id="pg-plots-title">Start with the space.<br /><em>Make it your own.</em></h2></div><div className="pc-living-grid"><figure className="pc-living-photo"><ResponsiveImage src="/assets/Palam City -1.jpg.webp" alt="Green residential surroundings in Haldwani" sizes="(max-width: 800px) 100vw, 45vw" /><figcaption>Room to shape the home you imagine.</figcaption></figure><div className="pc-amenities">{[['Choose your scale', 'Plots range from 1,000 to 2,000 square feet, giving you flexibility for a compact first home or a larger family haven.'], ['Own the design', 'Buyers design and build their own home rather than choosing from pre-built units.'], ['Keep nature close', 'Paloma Greens is built around the idea that luxury living and green space belong together.']].map(([title, text], i) => <details className="pc-detail" key={title} open={i === 0}><summary><Ruler size={24} strokeWidth={1.5} /><h3>{title}</h3><Plus className="pc-plus" size={20} /></summary><p>{text}</p></details>)}<div className="pc-amenity-note"><span>Designed around choice</span><p>Build a home that reflects how your household actually wants to live.</p></div></div></div></div></section>
      <section className="section-pad pc-location" id="pg-location" aria-labelledby="pg-location-title"><div className="container pc-split"><div><p className="eyebrow">03 / Connectivity and amenities</p><h2 id="pg-location-title">A greener setting.<br /><em>Connected to everyday life.</em></h2><p>Paloma Greens is positioned to offer good connectivity and modern amenities within its Haldwani setting.</p><div className="pc-connections"><span><Trees size={20} /> Nature-forward living</span><span><MapPin size={20} /> Haldwani location</span><span><Building2 size={20} /> Modern amenities</span></div></div><aside className="pc-address-card"><p className="eyebrow">A trusted name behind Paloma Greens</p><h3>Built on a legacy of trust.</h3><p>Paloma Greens is backed by Pal Colonisers, a developer with a genuine track record across Haldwani's real estate market.</p><a href="/about/the-pal-group">Discover the group <ArrowUpRight size={18} /></a></aside></div></section>
      <section className="section-pad pc-reasons" aria-labelledby="pg-reasons-title"><div className="container pc-split"><div><p className="eyebrow eyebrow-dark">Why choose Paloma Greens?</p><h2 id="pg-reasons-title">Luxury with room<br /><em>to breathe.</em></h2><a className="text-link" href="/industries/pal-colonisers/eco-town">Compare with Eco Town <ArrowUpRight size={18} /></a></div><div>{palomaGreensReasons.map(([title, text], i) => <article className="pc-reason" key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
      <section className="section-pad pc-faq" id="pg-faq" aria-labelledby="pg-faq-title"><div className="container pc-split"><div><p className="eyebrow eyebrow-dark">04 / Good to know</p><h2 id="pg-faq-title">Your questions,<br /><em>answered.</em></h2></div><div>{palomaGreensFaqs.map(([question, answer]) => <details className="pc-detail" key={question}><summary><h3>{question}</h3><Plus className="pc-plus" size={20} /></summary><p>{answer}</p></details>)}</div></div></section>
      <section className="section-pad pc-contact" id="pg-contact" aria-labelledby="pg-contact-title"><div className="container pc-split"><div><p className="eyebrow eyebrow-dark">05 / Visit or contact Paloma Greens</p><h2 id="pg-contact-title">Your next chapter<br /><em>starts here.</em></h2><p>You can reach the SM Pal Group team about Paloma Greens using the details below.</p><a className="button button-green" href="/contact">Enquire with our team <ArrowUpRight size={18} /></a></div><address><div><MapPin size={23} /><div><span>Visit Paloma Greens</span><p>Palam City, Devalchaur, Opposite Pal Ford, Rampur Road, Haldwani, 263139</p></div></div><div><Phone size={22} /><div><span>Call us</span><a href="tel:+919045599277">+91 90455 99277</a></div></div><div><Mail size={22} /><div><span>Email us</span><a href="mailto:marketing@smpalgroup.com">marketing@smpalgroup.com</a></div></div></address></div></section>
      <section className="section-pad pc-related" aria-labelledby="pg-related-title"><div className="container"><p className="eyebrow eyebrow-dark">Explore more about SM Pal Group's real estate projects</p><h2 id="pg-related-title">More places.<br /><em>The same commitment.</em></h2><p>Explore <a href="/industries/pal-colonisers/eco-town">Eco Town</a>, <a href="/industries/pal-colonisers/pallazio">Pallazio</a>, <a href="/industries/pal-colonisers/pal-sumeera-residency">Pal Sumeera Residency</a>, <a href="/industries/pal-colonisers/palam-city">Palam City</a>, and <a href="/industries/pal-colonisers/ram-ji-vihar">Ram Ji Vihar</a>, or visit the <a href={colonisers}>Pal Colonisers</a> page.</p><div className="pc-project-links">{routeGroups.colonisers.filter(item => item.href !== seo.path).map(item => <a key={item.href} href={item.href}>{item.label}<ArrowUpRight size={20} /></a>)}</div></div></section>
    </main><Footer />
  </div>;
}
