import React from "react";
import { createRoot, hydrateRoot } from "react-dom/client";
import App from "./App.jsx";
import { loadPage } from "./pages/SiteRouter.jsx";
import "./styles/fonts.css";
import "./styles/global.css";
import "./styles/responsive.css";
import "./styles/prateek.css";
import "./styles/about.css";
import "./styles/board.css";
import "./styles/pal-group.css";
import "./styles/home.css";
import "./styles/brand-consistency.css";
import "./styles/ownership.css";
import "./styles/industries.css";
import "./styles/pal-fresh-global.css";
import "./styles/pal-fresh-products.css";
import "./styles/frozzo-products.css";
import "./styles/prose.css";

const path = window.location.pathname.replace(/\/$/, "") || "/";
const { default: Page } = await loadPage(path);
const root = document.getElementById("root");
const app = <React.StrictMode><App Page={Page} path={path} /></React.StrictMode>;
if (root.hasChildNodes() && root.dataset.route === path) hydrateRoot(root, app);
else createRoot(root).render(app);
